### PR TITLE
Bump tendermint-rs to 0.38

### PR DESCRIPTION
**Pull request by yito88**

### CODE REVIEW

**Comment by Farhad-Shabani** [comment]
@erwanor appreciate merging this PR. Thanks!

**Comment by larry0x** [comment]
tendermint-rs 0.40 is already out. Need to bump to `0.40`...

**Comment by erwanor** [comment]
Sorry I was out for a bit, we will get a couple releases out shortly

**Review by erwanor — APPROVED** [review]

**Comment by erwanor** [comment]
@yito88 @larry0x heya, a few new releases are out:
- `0.16` (`tendermint@0.38`)
- `0.17` (`tendermint@0.39`)
- `0.18` (`tendermint@0.40`)

Sorry this took so long, we're going back to the regular cadence of updates now..

**Comment by larry0x** [comment]
Thank you!

**Comment by larry0x** [comment]
Thank you!

**Pull request merged**
